# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a76d1d37c696008ecada04c89cdb98900b9668a9df3a1431c2319be6bac6e106d5248ba5d76305d8645a3971c663aea8a8f93bb71cecb4cb83cbcbcdffd25471

test:
  secret_key_base: 5da3beb32fb1c2d4fcadd29dc635df3bf091c8a68b0ad95468200a90cb6dc2a5d60d6ba98a953f4d5a60f36da9886d13ff14c794af312eab304cd327dbc49812

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
